apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: todo-app-vpa
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: mongo-state   
  updatePolicy:
    updateMode: "Auto" 

